language: python
sudo: false

services:
  - mongodb

addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server

python:
- 2.7
- 3.4
- 3.5

before_install:
  - git clone https://github.com/nsls-ii/nsls2-ci ~/scripts
  - . ~/scripts/install-miniconda.sh
  - . ~/scripts/init-filestore.sh
  - . ~/scripts/init-metadatastore.sh

install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  - conda create -n testenv pip pytest python=$TRAVIS_PYTHON_VERSION six numpy pandas h5py coverage jsonschema jinja2 cytoolz pyyaml mongoengine tzlocal boltons pymongo pims tifffile doct channelarchiver filestore metadatastore
  - source activate testenv
  - pip install coveralls codecov
  - if [ $TRAVIS_PYTHON_VERSION = "2.7" ]; then
      pip install singledispatch;
    fi;
  - python -c "from filestore import utils, conf; utils.install_sentinels(conf.connection_config, 1)"
  - python setup.py install
  # Need to clean the repo or pytest gets confused why there are *two* copies
  # of all the python files
  - git clean -xfd

script:
  - coverage run run_tests.py

after_success:
  - coverage report -m
  - coveralls
  - codecov
