package:
  name: databroker
  version: {{ environ['GIT_DESCRIBE_TAG'] }}.post{{ environ['GIT_DESCRIBE_NUMBER'] }}

source:
  git_url: ../

build:
  number: 0
  string: {{ environ.get('GIT_BUILD_STR', '') }}_py{{ py }}

requirements:
  build:
    - python

  run:
    - python
    - pandas
    - pims
    - metadatastore >=v0.2.0
    - filestore >=v0.2.0
    - channelarchiver
    - six
    - tzlocal
    - singledispatch [py27]
    - doct
    - boltons

test:
  requires:
    - nslsii_dev_configuration
  imports:
    - databroker
    - databroker.testing
    - databroker.examples
    - databroker.examples.sample_data
    - databroker.utils

about:
  home: https://github.com/NSLS-II/databroker
  license: BSD
