name: CD

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Build two packages: databroker and bluesky-tiled-plugins.

      - uses: hynek/build-and-inspect-python-package@v2
        with:
          path: .
          upload-name-suffix: "-databroker"

      - uses: hynek/build-and-inspect-python-package@v2
        with:
          path: bluesky-tiled-plugins/
          upload-name-suffix: "-bluesky-tiled-plugins"

  publish:
    needs: [dist]
    environment: pypi
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: Packages-databroker
          path: dist

      - uses: actions/download-artifact@v4
        with:
          name: Packages-bluesky-tiled-plugins
          path: dist

      - uses: pypa/gh-action-pypi-publish@release/v1
